### ISSUE TITLE
Calling module other portal generates error

### ISSUE THREAD

**Issue by kestonpollard** [sachatrauwaen/OpenContent#154]
DNN 9.9.0
OC 4.5.0

Clicking on Switch Template > Choosing Other Portal as Source of content
generates general error:

**Message**: Input string was not in a correct format.
**StackTrace**:
**InnerMessage**: Input string was not in a correct format.
**InnerStackTrace**: 
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Satrabel.OpenContent.TemplateInit.rblDataSource_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Web.UI.WebControls.ListControl.OnSelectedIndexChanged(EventArgs e)
   at System.Web.UI.Page.<RaiseChangedEventsAsync>d__396.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()

**Comment by sachatrauwaen** [comment]
Fixed in OC v 5.0
