### ISSUE TITLE
Content Localization DNN and choose other module for Source of content

### ISSUE THREAD

**Issue by mvanlaar** [sachatrauwaen/OpenContent#21]
I've got a site with dnn content localization enabled. When i make the page translatable and I want to choose source of content in a different language I get this error in the error logs of dnn.

I've got the 3.2.2 version of the module on dnn 9.1

2017-05-29 10:31:17,831 [WIN-7H47NBKLBFK][Thread:36][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: I. Path '', line 96, position 2.
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JToken.Parse(String json)
   at Satrabel.OpenContent.Components.OpenContentInfo.get_JsonAsJToken()
   at Satrabel.OpenContent.Components.OpenContentController.AddContent(OpenContentInfo content, Boolean index, FieldConfig indexConfig)
   at Satrabel.OpenContent.Components.FeatureController.ImportModule(Int32 moduleId, String Content, String version, Int32 userId)
   at DotNetNuke.Entities.Modules.ModuleController.LocalizeModuleInternal(ModuleInfo sourceModule)
2017-05-29 10:33:15,236 [WIN-7H47NBKLBFK][Thread:55][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Satrabel.OpenContent.TemplateInit.rblDataSource_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Web.UI.WebControls.ListControl.OnSelectedIndexChanged(EventArgs e)
   at System.Web.UI.Page.RaiseChangedEvents()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2017-05-29 10:33:15,240 [WIN-7H47NBKLBFK][Thread:55][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=118&error=Input+string+was+not+in+a+correct+format.&content=0
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Satrabel.OpenContent.TemplateInit.rblDataSource_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Web.UI.WebControls.ListControl.OnSelectedIndexChanged(EventArgs e)
   at System.Web.UI.Page.RaiseChangedEvents()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by robsiera** [comment]
The code mentioned in your error has been changes. So you could try to install the latest dev version which you can [download here](https://ci.appveyor.com/project/sachatrauwaen/opencontent/build/02.00.00.766-feature/Ports-Adapters/artifacts). Beware to make backup of db and files first, just in case. However, I am running this version in production, so I'm confidant to suggest it.

**Comment by robsiera** [comment]
In [this version](https://ci.appveyor.com/project/sachatrauwaen/opencontent/build/artifacts) I added some extra logging code to better help understand what your problem is.

**Comment by mvanlaar** [comment]
With the latest dev version I'm unable to reproduce the problem.
