### ISSUE TITLE
Lots of error logs (General Exceptions)

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#68]
Example of the errors:

UrlRewriter.UrlRuleConfig:GetConfig Failed
ExceptionMessage:Null object cannot be converted to a value type.
PortalId:0
Exception Type:System.InvalidCastException
Message:
Null object cannot be converted to a value type.
Stack Trace:(TRUNCATED TO 500 CHARS): at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) at System.Convert.ChangeType(Object value, Type conversionType) at PetaPoco.Database.ExecuteScalar[T](String sql, Object[] args) at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteScalar[T](String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args) at DotNetNuke.Data.SqlDataProvider.ExecuteScalar[T](String procedureName, Object[] commandParameters) at Satra

**Comment by sachatrauwaen** [comment]
Is this related to opencontent ?
can you join a non truncated stacktrace ?

**Comment by b-creative** [comment]
How do I join a non truncated stacktrace?

**Comment by sachatrauwaen** [comment]
You most of the time find them in /Portals/_default/logs

**Comment by b-creative** [comment]
2019-04-24 08:40:50.430+02:00 [vs6637][D:2][T:10][ERROR] Satrabel.HttpModules.Config.UrlRuleConfiguration - System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at PetaPoco.Database.ExecuteScalar[T](String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteScalar[T](String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteScalar[T](String procedureName, Object[] commandParameters)
   at Satrabel.Services.Log.UrlRule.UrlRuleController.AddUrlRule(UrlRuleInfo objUrlRule)
   at Satrabel.HttpModules.Config.UrlRuleConfiguration.GenerateConfig(Int32 portalId)

**Comment by sachatrauwaen** [comment]
This is not opencontent related. It's OpenUrlRewriter related.

Please post this in openurl rewriter repository.

**Comment by Scippy** [comment]
I've the same issue but on OpenUrlRewriter there is not Issue section. Where I can post? Where I can find a solution?
@b-creative have you found a solution?

**Comment by b-creative** [comment]
Hi @Scippy 
I stopped using the OpenUrlRewriter and only use the DNN_OpenContentProvider combined with the OpenContent module.

**Comment by Scippy** [comment]
@b-creative thanks for reply but this is not a solution for me. I use OpenUrlRewriter in a lot of my websites combined with Ventrian modules provider. I'm no able to stop using it.
I think it could be a little mistake with fast solution if anyone understand how fix it.

**Comment by sachatrauwaen** [comment]
Hi, I have open the issue section on the openurlrewriter github
https://github.com/sachatrauwaen/OpenUrlRewriter/issues

And please post a full log of an exception, the one included here is not complete
