### ISSUE TITLE
JSON JavaScriptSerializer errors after saving.

### ISSUE THREAD

**Issue by robert-m** [sachatrauwaen/OpenContent#93]
Hi Sacha! 

I'm hoping you can point me in the right direction on how to resolve this issue I'm getting a lot lately with OC v4.3.

After someone adds in new data and clicks the save button, it will take about 2-5mins for it to save back into the database. Then it redirects back to the page with the following error below.

Restarting the AppPool and deleting the AppData/OpenContent folder resolves the problem but the issue comes back after a short while. Do you have any idea why this is happening? :-)

`Message:Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property. Parameter name: input`

---
``InnerStackTrace : at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Satrabel.OpenContent.Components.Json.JsonUtils.JsonToDictionary(String json)
   at Satrabel.OpenContent.Components.Render.RenderEngine.GenerateListOutput(Page page, TemplateManifest templateManifest, TemplateFiles files, IEnumerable`1 dataList, String settingsJson)
   at Satrabel.OpenContent.Components.Render.RenderEngine.Render(Page page)
   at Satrabel.OpenContent.View.OnLoad(EventArgs e)``

**Comment by Timo-Breumelhof** [comment]
Please upgrade to OC 4.6.0 if the issue remains, please let us know. Closing for now.
